baseURL = 'https://candidcryptopodcast.com/'
locale = 'en-us'
title = 'Candid Crypto Podcast'

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]
  mainSections = ["articles", "podcast", "videos"]
  defaultColor = "auto"
  sitename    = "Candid Crypto Podcast"
  description = "A beginner-friendly crypto podcast by Liam Stojanovic and Michael Edelheit"
  ogimage     = "https://f002.backblazeb2.com/file/candid-crypto-public/og-image.png"

[[params.socialIcons]]
  name = "discord"
  url = "https://discord.gg/Pu2hCfsdwz"

[[params.socialIcons]]
  name = "youtube"
  url = "https://www.youtube.com/channel/UC-zsyn8m_AqE3sfkLUMi99g"

[[params.socialIcons]]
  name = "applepodcasts"
  url = "https://podcasts.apple.com/ca/podcast/candid-crypto/id1564765880"

[[params.socialIcons]]
  name = "spotify"
  url = "https://open.spotify.com/show/6YXtKs9cvMU3XwvlqBegU7?si=ssXqIz0IQTyeWnSF7ZYILQ&dl_branch=1"

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[[menu.main]]
  name = "Podcasts"
  url = "/podcast/"
  weight = 20

[[menu.main]]
  name = "Videos"
  url = "/videos/"
  weight = 30
